# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\Downloads\bilibili-application-master\live\danmuji_2.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(51, 44, 102);\n"
"border: none;\n"
"\n"
"                    ")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.top_menu = QtWidgets.QFrame(self.frame)
        self.top_menu.setMaximumSize(QtCore.QSize(10000, 35))
        self.top_menu.setStyleSheet("background-color: rgb(175, 165, 200);\n"
"")
        self.top_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_menu.setObjectName("top_menu")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.top_menu)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame1 = QtWidgets.QFrame(self.top_menu)
        self.frame1.setMinimumSize(QtCore.QSize(100, 35))
        self.frame1.setStyleSheet("QPushButton:hover{\n"
"    padding-bottom: 5px;\n"
"}")
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.maximize = QtWidgets.QPushButton(self.frame1)
        self.maximize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/top_menu/maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximize.setIcon(icon)
        self.maximize.setIconSize(QtCore.QSize(18, 18))
        self.maximize.setObjectName("maximize")
        self.horizontalLayout_2.addWidget(self.maximize)
        self.minimize = QtWidgets.QPushButton(self.frame1)
        self.minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/top_menu/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize.setIcon(icon1)
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_2.addWidget(self.minimize)
        self.close = QtWidgets.QPushButton(self.frame1)
        self.close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/top_menu/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon2)
        self.close.setObjectName("close")
        self.horizontalLayout_2.addWidget(self.close)
        self.horizontalLayout_4.addWidget(self.frame1)
        self.verticalLayout_4.addWidget(self.top_menu)
        self.main_menu = QtWidgets.QFrame(self.frame)
        self.main_menu.setStyleSheet("")
        self.main_menu.setObjectName("main_menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_menu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.list = QtWidgets.QFrame(self.main_menu)
        self.list.setStyleSheet("background-color: rgb(107, 95, 145);")
        self.list.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.list.setFrameShadow(QtWidgets.QFrame.Raised)
        self.list.setObjectName("list")
        self.horizontalLayout.addWidget(self.list)
        self.log = QtWidgets.QVBoxLayout()
        self.log.setObjectName("log")
        self.frame_3 = QtWidgets.QFrame(self.main_menu)
        self.frame_3.setStyleSheet("background-color: rgb(107, 95, 145);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.te_0 = QtWidgets.QTextEdit(self.frame_3)
        self.te_0.setGeometry(QtCore.QRect(10, 10, 191, 351))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.te_0.setFont(font)
        self.te_0.setStyleSheet("font: 14pt \"微軟正黑體\"; \n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"                            ")
        self.te_0.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.te_0.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.te_0.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.te_0.setReadOnly(True)
        self.te_0.setObjectName("te_0")
        self.log.addWidget(self.frame_3)
        self.frame_6 = QtWidgets.QFrame(self.main_menu)
        self.frame_6.setStyleSheet("background-color: rgb(107, 95, 145);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.le_0 = QtWidgets.QLineEdit(self.frame_6)
        self.le_0.setGeometry(QtCore.QRect(10, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.le_0.setFont(font)
        self.le_0.setStyleSheet("font: 13pt \"微軟正黑體\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.le_0.setObjectName("le_0")
        self.log.addWidget(self.frame_6)
        self.log.setStretch(0, 10)
        self.log.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.log)
        self.danmu = QtWidgets.QVBoxLayout()
        self.danmu.setObjectName("danmu")
        self.frame_4 = QtWidgets.QFrame(self.main_menu)
        self.frame_4.setStyleSheet("background-color: rgb(107, 95, 145);\n"
"\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.te_1 = QtWidgets.QTextEdit(self.frame_4)
        self.te_1.setGeometry(QtCore.QRect(13, 10, 191, 351))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.te_1.setFont(font)
        self.te_1.setStyleSheet("font: 14pt \"微軟正黑體\"; \n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;\n"
"                            ")
        self.te_1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.te_1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.te_1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.te_1.setReadOnly(True)
        self.te_1.setObjectName("te_1")
        self.danmu.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.main_menu)
        self.frame_5.setStyleSheet("background-color: rgb(107, 95, 145);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.le_1 = QtWidgets.QLineEdit(self.frame_5)
        self.le_1.setGeometry(QtCore.QRect(10, 10, 201, 21))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.le_1.setFont(font)
        self.le_1.setStyleSheet("font: 13pt \"微軟正黑體\";\n"
"color: rgb(255, 255, 255);\n"
"font-weight: bold;")
        self.le_1.setObjectName("le_1")
        self.danmu.addWidget(self.frame_5)
        self.danmu.setStretch(0, 10)
        self.danmu.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.danmu)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout_4.addWidget(self.main_menu)
        self.verticalLayout_4.setStretch(0, 1)
        self.horizontalLayout_3.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.close.clicked.connect(MainWindow.close)
        self.minimize.clicked.connect(MainWindow.showMinimized)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

import image_rc
